#!/bin/bash

set -xe

fqbn_path="/tmp/fqbn.txt" 
port_addr_path="/tmp/paddr.txt" 

[[ -f $fqbn_path ]] || init-ino
[[ -f $port_addr_path ]] || init-ino

arduino-cli compile --fqbn "$(cat $fqbn_path)" "$1"
arduino-cli upload -p "$(cat $port_addr_path)" --fqbn "$(cat $fqbn_path)" "$1"
